version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      # ホットリロードのためのボリュームマウント用に作業ディレクトリを指定
      - type: bind
        source: ./frontend
        target: /app
      # - type: bind
      #   source: ./frontend/public
      #   target: /app/public
      # - type: bind
      #   source: ./frontend/index.html
      #   target: /app/index.html
      # - type: bind
      #   source: ./frontend/vite.config.js
      #   target: /app/vite.config.js
      - type: volume
        source: node_modules
        target: /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    env_file:
      - ./backend/.env.development
    environment:
      - ENVIRONMENT=development
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
    depends_on:
      db:
        condition: service_healthy
      dynamodb-local:
        condition: service_started
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=rss_reader
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    # build:
    #   context: ./db
    #   dockerfile: Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    user: root
    ports:
      - "8001:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    environment:
      - AWS_REGION=ap-northeast-1
    volumes:
      - ./dynamodb_data:/data
    networks:
      - app-network

volumes:
  mysql_data:
  node_modules:

networks:
  app-network:
    driver: bridge