version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/default-images:/app/public/default-images
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev 

volumes:
  default_images: 