version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_API_URL=/api
    volumes:
      # ホットリロードのためのボリュームマウント用に作業ディレクトリを指定
      - type: bind
        source: ./frontend/src
        target: /app/src
      - type: bind
        source: ./frontend/public
        target: /app/public
      - type: bind
        source: ./frontend/index.html
        target: /app/index.html
      - type: bind
        source: ./frontend/vite.config.js
        target: /app/vite.config.js
      - type: volume
        source: frontend_node_modules
        target: /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/rss_reader
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rss_reader
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge