version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      # ホットリロードのためのボリュームマウント用に作業ディレクトリを指定
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__
    env_file:
      - ./backend/.env.development
    environment:
      - ENVIRONMENT=development
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
    depends_on:
      dynamodb-local:
        condition: service_started
    networks:
      - app-network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    user: root
    ports:
      - "8001:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    environment:
      - AWS_REGION=ap-northeast-1
    volumes:
      - ./dynamodb_data:/data
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge