"""make_feed_id_nullable_in_ai_summaries

Revision ID: 37ad47519ce0
Revises: 910c4b004960
Create Date: 2025-03-17 01:57:20.687605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37ad47519ce0'
down_revision: Union[str, None] = '910c4b004960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_summaries', 'feed_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_summaries', 'feed_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
