"""add columns to table_favorite_articles

Revision ID: 604112efa96c
Revises: 48ed5c5da985
Create Date: 2025-02-14 06:42:44.725233

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import Text

# revision identifiers, used by Alembic.
revision: str = "604112efa96c"
down_revision: Union[str, None] = "48ed5c5da985"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "favorite_articles",
        sa.Column("article_image", sa.String(length=2083), nullable=True),
    )
    op.add_column(
        "favorite_articles",
        sa.Column(
            "article_categories", postgresql.JSON(astext_type=Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("favorite_articles", "article_categories")
    op.drop_column("favorite_articles", "article_image")
    # ### end Alembic commands ###
