"""add_is_external_to_favorite_articles

Revision ID: 910c4b004960
Revises: a7e2d0458032
Create Date: 2025-03-17 01:43:10.665139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910c4b004960'
down_revision: Union[str, None] = 'a7e2d0458032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
