"""add_is_external_to_favorite_articles

Revision ID: a7e2d0458032
Revises: 729a3d1d3a0e
Create Date: 2025-03-17 01:39:13.348598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7e2d0458032'
down_revision: Union[str, None] = '729a3d1d3a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('article_link', table_name='article_summaries')
    op.drop_index('ix_article_summaries_id', table_name='article_summaries')
    op.drop_table('article_summaries')
    op.alter_column('ai_summaries', 'article_link',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.add_column('favorite_articles', sa.Column('is_external', sa.Boolean(), nullable=True))
    op.alter_column('favorite_articles', 'feed_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('feeds', 'url',
               existing_type=mysql.VARCHAR(length=2083),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('read_articles', 'article_link',
               existing_type=mysql.VARCHAR(length=2083),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('read_articles', 'article_link',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=2083),
               existing_nullable=False)
    op.alter_column('feeds', 'url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=2083),
               existing_nullable=False)
    op.alter_column('favorite_articles', 'feed_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('favorite_articles', 'is_external')
    op.alter_column('ai_summaries', 'article_link',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.create_table('article_summaries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_link', mysql.VARCHAR(length=767), nullable=False),
    sa.Column('summary', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_article_summaries_id', 'article_summaries', ['id'], unique=False)
    op.create_index('article_link', 'article_summaries', ['article_link'], unique=True)
    # ### end Alembic commands ###
